resource_group_name   = "terraformlab   "
storage_account_name  = "stateterraform5000"
container_name        = "labstate"
key                   = "labstate.tfstate"
access_key            = "UIVxq+DDG9pwTsQyh9E4vzjb1Gwk4Y32Gaa6foacFzhIMXBY+C0YYWv+H9wqbATy1fHmlKIE5j9inC+/iJ3qTA=="